apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: hhttps://github.com/leslie885/capstone.git
    targetRevision: HEAD
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: capstone
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
