apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: leslie885/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: api
          volumeMounts:
            - name: db-schema
              mountPath: /path/to/words.sql   # Mount path in your container
              subPath: words.sql
      volumes:
        - name: db-schema
          configMap:
            name: words-configmap   # Reference your existing ConfigMap here
