apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
data:
  words.sql: |
    -- Contents of your words.sql file
    INSERT INTO words (word) VALUES ('example1'), ('example2'), ('example3');
    -- Add any further initialization SQL statements here

