apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  postgres-password: cG9zdGdyZXMtcGFzc3dvcmQ=  # 'postgres-password' base64 encoded
  database-url: cG9zdGdyZXM6cGFzc3dvcmRAMTI3LjAuMC4xOjU0MzIvbXlkYg==  # 'postgres:password@127.0.0.1:5432/mydb' base64 encoded
